execute-coordinator:
	g++ --std=c++11 -pthread coordinator.cpp -o coordinator.out
	./coordinator.out coordinator.txt

execute-participant1:
	g++ --std=c++11 -pthread participant.cpp -o participant.out
	./participant.out participant1.txt

execute-participant2:
	g++ --std=c++11 -pthread participant.cpp -o participant.out
	./participant.out participant2.txt

execute-participant3:
	g++ --std=c++11 -pthread participant.cpp -o participant.out
	./participant.out participant3.txt

execute-participant4:
	g++ --std=c++11 -pthread participant.cpp -o participant.out
	./participant.out participant4.txt

compile-coordinator:
	g++ --std=c++11 -pthread coordinator.cpp -o coordinator.out
	
compile-participant:
	g++ --std=c++11 -pthread participant.cpp -o participant.out
