execute-bnserver:
	g++ --std=c++11 -pthread bnserver.cpp -o bnserver.out
	./bnserver.out bnconfig.txt

execute-nameserver1:
	g++ --std=c++11 -pthread nameserver.cpp -o nameserver.out
	./nameserver.out ns_390.txt

execute-nameserver2:
	g++ --std=c++11 -pthread nameserver.cpp -o nameserver.out
	./nameserver.out ns_757.txt

compile-bnserver:
	g++ --std=c++11 -pthread bnserver.cpp -o bnserver.out

compile-nameserver:
	g++ --std=c++11 -pthread nameserver.cpp -o nameserver.out